<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2016/11/03 09:56:55
sfConfig::add(array(
  'mod_sfguardforgotpassword_enabled' => true,
  'mod_sfguardforgotpassword_view_class' => 'sfPHP',
));
