<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2016/11/04 10:53:40
sfConfig::add(array(
  'mod_sfguardforgotpassword_enabled' => true,
  'mod_sfguardforgotpassword_view_class' => 'sfPHP',
));
