<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2016/11/03 09:29:53
sfConfig::add(array(
  'mod_sfguardregister_enabled' => true,
  'mod_sfguardregister_view_class' => 'sfPHP',
));
