<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2016/10/28 09:38:52
sfConfig::add(array(
  'app_active_days' => 30,
  'app_max_jobs_on_homepage' => 1,
  'app_max_jobs_on_category' => 1,
));
