<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2016/11/04 10:43:02
sfConfig::add(array(
  'app_active_days' => 30,
  'app_max_jobs_on_homepage' => 1,
  'app_max_jobs_on_category' => 1,
));
