<?php

/**
 * PluginJobeetCategoryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginJobeetCategoryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginJobeetCategoryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginJobeetCategory');
    }
}