<?php

/**
 * PluginJobeetJobTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginJobeetJobTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginJobeetJobTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginJobeetJob');
    }
}