<?php

/**
 * JobeetAffiliateTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class JobeetAffiliateTable extends Doctrine_Table
{
	public function countToBeActivated()
	{
		$q = $this->createQuery('a')
		->where('a.is_active = ?', 0);

		return $q->count();
	}
	public function getForToken(array $parameters)
	{
		$affiliate = Doctrine_Core::getTable('JobeetAffiliate') ->findOneByToken($parameters['token']);
		if (!$affiliate || !$affiliate->getIsActive())
		{
			throw new sfError404Exception(sprintf('Affiliate with token "%s" does not exist or is not activated.', $parameters['token']));
		}
	
		return $affiliate->getActiveJobs();
	}
	

}